## *Compte Rendu du Numpy*

*On va importer les librairies numpy et time et la fonction log du module math*

In [1]:
import numpy as np
import time
from math import log

### Vectorisation

* En python normal, cela se ferait élément par élément en utilisant quelque
chose comme une boucle for, donc quatre calculs l'un après l'autre. Si
chaque calcul prend 1 seconde, ce serait 4 secondes pour terminer le calcul.

* Cependant, numpy multipliera en fait deux vecteurs ensemble [2,2,2,2] et
[2,4,6,8](numpy "étire" la valeur scalaire 2 en un vecteur en utilisant
quelque chose appelé diffusion. Chacun des quatre calculs distincts est
effectué simultanément en parallèle. 
Donc en termes de temps, le calcul est réalisé en 1 seconde (chaque calcul
prend 1 seconde, mais ils sont tous réalisés en même temps).

* Une quadruple amélioration théorique de la vitesse (une forme de traitement parallèle).

* Sachez simplement que:
   * la vectorisation n'est pas illimitée et dépend du matériel
   * La vectorisation n'est pas la seule forme de parallélisation

#### Test de rapidité

*Les structures de Numpy sont très rapides dans la manipulation 
des données de taille très large puisque la bibliothèque s'appuie
sur le langage C*

In [2]:
#Définition d'une structure Numpy
my_arr = np.arange (1000000)
#Définition d'une structure Native
my_list=list(range (1000000))

In [3]:
#Temps d'exécution du 10*calcul du double d'une structure Numpy
start_time = time.time()
for _ in range (10): my_arr2 = my_arr * 2
print("--- %s Numpy seconds ---" % (time.time() - start_time))
#Temps d'exécution du 10*calcul du double d'une structure Native
start_time = time.time()
for _ in range (10): my_list2 = [x * 2 for x in my_list]
print("--- %s Native seconds ---" % (time.time() - start_time))

--- 0.015990734100341797 Numpy seconds ---
--- 0.6946871280670166 Native seconds ---


In [4]:
#Définition d'une structure Numpy
my_arr = np.array([[1, 2, 3, 4]])
#Définition d'une structure Native
my_list=list([1, 2, 3, 4])

In [5]:
#Temps d'exécution du double en Numpy
start_time = time.time()
my_arr2 = my_arr * 2
print("--- %s Vectorization Numpy seconds ---" % (time.time() - start_time))
#Temps d'exécution du double en Native
start_time = time.time()
my_list2 = [x * 2 for x in my_list]
print("--- %s No Vectorization Native seconds ---" % (time.time() - start_time))

--- 0.0 Vectorization Numpy seconds ---
--- 0.014858007431030273 No Vectorization Native seconds ---


Pour savoir la version numpy on exécute la commande :

In [6]:
print(np.__version__)

1.23.5


Création de ndarray à partir de d'autres structures natives :

Pour créer un ndarray à partir d'une liste on utilise la méthode np.arrray().

In [7]:
arrfromlist = np.array([1, 2, 3, 4, 5])
#Afficher un ndarray
print(arrfromlist)

[1 2 3 4 5]


On vérifie le type ndarray :

In [8]:
print(type(arrfromlist))

<class 'numpy.ndarray'>


Créer un ndarray à partir d'un tuple : en utilisant la méthode np.array()

In [9]:
arrfromtuple = np.array(('car', 'plane', 'truck'))
print(arrfromtuple)

['car' 'plane' 'truck']


Créer un ndarray à partir d'un set : en utilisant np.array()

In [10]:
arrfromset = np.array({1, 2, 3, 4, 5})
#Afficher un ndarray
print(arrfromset)

{1, 2, 3, 4, 5}


In [11]:
#vérifier le type ndarray!
print(type(arrfromset))

<class 'numpy.ndarray'>


Créer un ndarray à partir d'un range : np.array(range(n))

In [12]:
arrfromrange = np.array(range(6))
print(arrfromrange)

[0 1 2 3 4 5]


ou vous pouvez faire : arrfromrange= np.arange(0, 6, 1)

##### Création de tableaux avec des valeurs spécifiques

##### np.ones

In [13]:
#10 couples de 1
ones = np.ones((10, 2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


np.zeros((m, l, c)) : donne array avec m matrices dont chaque matrice de dimension l*c;les élèments sont tous nuls.

In [14]:
#5 matrices ; chaque matrice est de 3 lignes et 3 colonnes : notre array remplie de zéros. 
zeros = np.zeros((5, 3, 3))
print(zeros)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


##### np.random.randint

np.random.randint(m, size=(l, c)) : array de l lignes et c colonnes dont les élèments compris entre 0 et m-1.

In [15]:
random_array = np.random.randint(10, size=(5, 3))
print(random_array)

[[6 1 8]
 [2 8 0]
 [3 6 8]
 [6 2 7]
 [1 9 0]]


##### np.random.random

np.random.random((l, c)) : array de l lignes et c colonnes dont les élèments compris entre 0 et 1 .

In [16]:
# Random 0-1 array
random_array2 =np.random.random((5, 3))
print(random_array2)

[[0.75477808 0.25315391 0.67667975]
 [0.90845134 0.09821001 0.90698433]
 [0.21212484 0.82807691 0.45136604]
 [0.75186567 0.25074333 0.07291627]
 [0.96367078 0.31410802 0.25097604]]


Vous pouvez utiliser aussi np.random.rand(l,c).

In [17]:
random_array2 =np.random.rand(5, 3)
random_array2

array([[0.53401716, 0.30594292, 0.4104454 ],
       [0.36061071, 0.73757211, 0.04780169],
       [0.88113518, 0.27196328, 0.49220417],
       [0.75696233, 0.96257376, 0.54701518],
       [0.0473412 , 0.31740945, 0.68698769]])

##### np.seed()

On l'uiliser pour avoir random array avec le même ensemble très pratique dans le cas du training and test data.

Re-exécuter la cellule en dessous donne le meme résultat.

In [18]:
np.random.seed(0)
random_array=np.random.randint(10, size=(5, 3))
np.random.seed(0)
random_array2=np.random.randint(10, size=(5, 3))
print(random_array)
print(random_array2)

[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]
 [8 8 1]]
[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]
 [8 8 1]]


### Dimensions de ndarray

Créer un ndarray arr0d de dimension=simple=0 contenat un seul élèment.

In [19]:
arr0d = np.array(10)
#Afficher un ndarray
print(arr0d)
#Afficher la dimension
print(arr0d.ndim)

10
0


Créer un ndarray 1 dimension

In [20]:
arr1d = np.array([10,11])
#Afficher un ndarray
print(arr1d)
#Afficher la dimension
print(arr1d.ndim)

[10 11]
1


Créer un ndarray 2 dimensions

In [21]:
arr2d = np.array([[10,11],[12,13]])
#Afficher un ndarray
print(arr2d)
#Afficher la dimension
print(arr2d.ndim)

[[10 11]
 [12 13]]
2


Créer un ndarray 3 dimensions

In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#Afficher un ndarray
print(arr3d)
#Afficher la dimension
print(arr3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


Créer un ndarray multi dimensions

In [23]:
arr5d = np.array([1, 2, 3, 4], ndmin=5)
#Afficher un ndarray
print(arr5d)
#Afficher la dimension
print('number of dimensions :', arr5d.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


#### Accès à un élément

In [24]:
#1er élément d'un ndarray 1d
print(arrfromlist[0])
#2ème élément d'un ndarray 1d
print(arrfromlist[1])

1
2


In [25]:
#ligne 0 colonne 1 d'un ndarray 2d
print(arr2d[0,1])
#ligne 2 colonne 0 d'un ndarray 2d
#print(arr2d[2,0])#index 2 is out of bounds for axis 0 with size 2
#ligne 0 d'un ndarray 2d , il s'agit de la première ligne.
print(arr2d[0])

11
[10 11]


In [26]:
#Troisième élément du deuxième tableau du premier tableau 
print(arr3d[0, 1, 2])
#ou
print(arr3d[-2, -1, -1])
#1ère matrice
print(arr3d[0])
#2ème ligne de la 1ère matrice
print(arr3d[0,1])

6
6
[[1 2 3]
 [4 5 6]]
[4 5 6]


#### Nombre d'éléments d'un ndarray

In [27]:
print(arr0d.size)
print(arr1d.size)
print(arr2d.size)
print(arr3d.size)

1
2
4
12


### Slicing

* [start=0:end:step=1] end est exclu

In [28]:
#2ème et 3ème éléments
print(arrfromlist[1:3])
#quatres premiers éléments
print(arrfromlist[:4])
#deux avants derniers éléments
print(arrfromlist[-3:-1])

[2 3]
[1 2 3 4]
[3 4]


In [29]:
#Récupération de la deuxième ligne
print(arr2d[1, 0:2])
#ou
print(arr2d[1, :])
#Récupération de la première colonne
print(arr2d[:, 0])
#Récupération du premier élement de la ligne 0 colonne 0
print(arr2d[-2:-1,-2:-1])

[12 13]
[12 13]
[10 12]
[[10]]


In [30]:
#Récupération des deux premières valeurs des deux premières lignes des deux premiers tableaux
print(arr3d[:2, :2, :2])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [31]:
#Type i
print(arrfromlist.dtype)
#Type U
print(arrfromtuple.dtype)

int32
<U5


In [32]:
#Création d'un tableau string
arrstring = np.array([1, 2, 3, 4], dtype='S')
print(arrstring.dtype)

|S1


In [33]:
#ou
arrstring = np.array([1, 2, 3, 4], dtype='S1')
print(arrstring.dtype)

|S1


In [34]:
#valueerror
#arrvalueerror = np.array(['a', '2', '3'], dtype='i')
#Conversion de type d'un tableau existant
#La astype(type)crée une copie du tableau.
#Le type de données peut être spécifié à l'aide d'une chaîne, comme 'f'pour float
arrtoconvert = np.array([1.1, 2.1, 3.1])
arrconveted = arrtoconvert.astype('i')
print(arrconveted)
print(arrconveted.dtype)

[1 2 3]
int32


Copie ou vue :

La copie recrée un autre tableau

Alors que la vue ne crée qu'une référence

In [35]:
#Créer une copie
copie = arrfromlist.copy()
copie[0] = 42
print(arrfromlist)
print(copie)
#créer une vue
view = arrfromlist.view()
view[0] = 40
print(arrfromlist)
print(view)

[1 2 3 4 5]
[42  2  3  4  5]
[40  2  3  4  5]
[40  2  3  4  5]


* Savoir si le tableau est une vue
  * La copie renvoi None avec base attribute.
  * La vue renvoie le tableau d'origine.

In [36]:
print(copie.base)
print(view.base)

None
[40  2  3  4  5]


La forme d'un tableau est le nombre d'éléments dans chaque dimension.

In [37]:
print(arr0d.shape)
print(arr1d.shape)
print(arr2d.shape)
print(arr3d.shape)
print(arr5d.shape)

()
(2,)
(2, 2)
(2, 2, 3)
(1, 1, 1, 1, 4)


En remodelant, nous pouvons ajouter ou supprimer des dimensions ou 
modifier le nombre d'éléments dans chaque dimension.

les éléments nécessaires au remodelage sont égaux dans les deux formes.


In [38]:
#1d à 2d
arr1dtoreshape = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr2dreshaped = arr1dtoreshape.reshape(4, 3)
print(arr2dreshaped)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
#1d à 3d
arr3dreshaped = arr1dtoreshape.reshape(2,2, 3)
print(arr3dreshaped)
#dimension inconnue Passez -1comme valeur et NumPy calculera ce nombre pour vous.
#Remarque : Nous ne pouvons pas passer -1à plus d'une dimension.
arr4dreshaped = arr1dtoreshape.reshape(2,2,1,-1 )
print(arr4dreshaped)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]]


**Aplatir un tableau signifie convertir un tableau multidimensionnel en un tableau 1D.**

**Nous pouvons utiliser reshape(-1) ou reshape(nbr_ets) pour le faire.**

In [40]:
arr1dback=arr4dreshaped.reshape(-1)
print(arr1dback)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Parcourir un tableau** 

In [41]:
#1d
for x in arr1d:
  print(x)

10
11


In [42]:
#2d renvoie les couples
for x in arr2d:
  print(x)
#2d renvoie les individus
#Pour renvoyer les individus, nous devons itérer les tableaux dans chaque dimension
for x in arr2d:
    for y in x:
        print(y)

[10 11]
[12 13]
10
11
12
13


In [43]:
#ou utiliser tout simplement
for x in arr2d.reshape(-1):
    print(x)

10
11
12
13


### Jointure

Avec l'intermédiaire d'une fonction concatenate(arr1,arr2,axe_jointure)

Les deux tableaux doivent avoir la même dimension

In [44]:
#sans axe :le seul axe présent
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arrjoined = np.concatenate((arr1, arr2))
print(arrjoined)

[1 2 3 4 5 6]


In [45]:
#axe lignes
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arrjoined2d = np.concatenate((arr1, arr2), axis=0)
print(arrjoined2d)
#axe colonnes (ne marche si le nombre d'élements n'est pas le même ds les dexu tableaux=)
arrjoined2d = np.concatenate((arr1, arr2), axis=1)
print(arrjoined2d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### Empilement

L'empilement est identique à la concaténation,

la seule différence est que l'empilement se fait le long d'un nouvel axe.

A l'aide de la fonction stack(stack((arr1, arr2), axis=0))

L'empilement crée de nouvelles dimensions lorsqu'il se fait sur de nvx axes

si l'emplilement se fait selon les anciens axes=concténation

In [46]:
#1d avec nouvel axe
#on peut pas incrémenter que d'un seul axe 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arrstack = np.stack((arr1, arr2), axis=1)
print(arrstack) 
#2d tester les valeurs 0, 1 et 2 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arrstack = np.stack((arr1, arr2), axis=2)
#arrstack = np.hstack((arr1, arr2))
#arrstack = np.vstack((arr1, arr2))
#arrstack = np.dstack((arr1, arr2))
print(arrstack)

[[1 4]
 [2 5]
 [3 6]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


#### Division

La fonction array_split() retourne un tableau de tableaux

In [47]:
arrtodivide = np.array([1, 2, 3, 4, 5, 6])
arrdivided = np.array_split(arrtodivide, 3)
#ajustement à partir de la fin à la différence de split() qui nécessite
#que le nombre d'élements soit divisible par le nbre de fractions
#arrdivided = np.array_split(arrtodivide, 4)
print(arrdivided)
#1er tableau
print(arrdivided[0])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [48]:
#2D split
arrtosplit = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], 
[16, 17, 18]])
arrsplited = np.array_split(arrtosplit, 3)
print(arrsplited)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [49]:
#2D split selon l'axe 1
arrsplited = np.array_split(arrtosplit, 3,axis=1)
print(arrsplited)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [50]:
#hsplit
arrsplited = np.hsplit(arrtosplit, 3)
print(arrsplited)
#vsplit
arrsplited = np.vsplit(arrtosplit, 3)
print(arrsplited)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


#### Recherche

Vous pouvez rechercher une certaine valeur dans un tableau 
et renvoyer les index qui correspondent.

Pour rechercher un tableau, utilisez la where()méthode.

In [51]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)
#tous les index des valeurs paires
x = np.where(arr%2 == 0)
print(x)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)


In [52]:
#Il existe une méthode appelée searchsorted()qui effectue une recherche binaire
#dans le tableau et renvoie 
#l'index où la valeur spécifiée serait insérée pour maintenir l'ordre de recherche.
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)
x = np.searchsorted(arr, 7, side='right')
print(x)
#recherche de plusieurs éléments
x = np.searchsorted(arr,[4,7])
print(x)

1
2
[0 1]


#### Tri

Cette méthode renvoie une copie du tableau, en laissant le tableau d'origine inchangé.

In [53]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
#indices en sortie
print(np.argsort(arr))
#2D
arr = np.array([['a', 'E', 'e'], [5, 0, 1]])
print(np.sort(arr))

[0 1 2 3]
[2 3 1 0]
[['E' 'a' 'e']
 ['0' '1' '5']]


### Filtre

A partir

Une liste d' index booléens est une liste de booléens correspondant aux index du tableau.

Si la valeur à un index est Trueque cet élément est contenu dans le tableau filtré, 

si la valeur à cet index est Falsecet élément est exclu du tableau filtré.


In [54]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [55]:
#Exemple dynamique
x.clear()
for a in arr:
    if a%2!=0:
        x.append(True)
    else:
        x.append(False)
newarr = arr[x]
print(newarr)

[41 43]


In [56]:
#liste définie par compréhension
x.clear()
x=arr>43
newarr = arr[x]
print(newarr)

[44]


In [57]:
newarr = arr[arr%2==0]
print(newarr)

[42 44]


### Fonctions

In [58]:
def myadd(x, y):
  return x+y
myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))
"""Fonctions systèmes dans Numpy"""
"""Fonctions arithmétiques
opérateurs arithmétiques + - * / mais non conditionnnelless
Fonctions arithmétiques acceptent le conditionnnement"""
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarradd = np.add(arr1, arr2)
#ou newarradd=arr1+arr2
print(newarradd)

[6 8 10 12]
[30 32 34 36 38 40]


In [59]:
#newarrsub = np.subtract(arr1, arr2)
newarrsub=arr1-arr2
print(newarrsub)

[-10 -10 -10 -10 -10 -10]


In [60]:
#newarrmult = np.multiply(arr1, arr2)
newarrmult = arr1* arr2
print(newarrmult)

[200 231 264 299 336 375]


In [61]:
#newarrdiv = np.divide(arr1, arr2)
newarrdiv= arr1/ arr2
print(newarrdiv)

[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]


In [62]:
#newarrpow = np.power(arr1, arr2)
newarrpow = arr1**arr2
print(newarrpow)

[ 1661992960   602408795           0  1487897765  1090519040 -1144744561]


In [63]:
#newarrmod = np.mod(arr1, arr2)
#newarrmod = arr1%arr2
newarrmod = np.remainder(arr1, arr2)
print(newarrmod)

[10 11 12 13 14 15]


In [64]:
newarrdivmod = np.divmod(arr1, arr2)
#newarrdivmod = arr1//arr2
print(newarrdivmod)
newarrabs = np.absolute(arr)
print(newarrabs)

(array([0, 0, 0, 0, 0, 0]), array([10, 11, 12, 13, 14, 15]))
[41 42 43 44]


In [65]:
#Arrondi
#arr = np.trunc([-3.1666, 3.6667])
arr = np.fix([-3.1666, 3.6667])
print(arr)
arr = np.around(3.1666, 2)
print(arr)

[-3.  3.]
3.17


In [66]:
#Logarithmique
#pour n'importe quelle base, il faut passer par une fonction personnalisée
arr = np.arange(1, 10)
print(np.log2(arr))
print(np.log10(arr))
print(np.log(arr))
nplog = np.frompyfunc(log, 2, 1)
print(nplog(100, 15))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
1.7005483074552052


In [67]:
#Exponenetiel
print(np.exp(arr))
#Carré
print(np.square(arr))
#Racine
print(np.sqrt(arr))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[ 1  4  9 16 25 36 49 64 81]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [68]:
#Somme axiale
newarr = np.sum([arr1, arr2], axis=1)
print(newarr)
#Somme cumulée
#La somme cumulative signifie ajouter partiellement les éléments du tableau.
#Par exemple, la somme partielle de [1, 2, 3, 4] serait
#[1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
newarr = np.cumsum(arr1)
print(newarr)

[ 75 135]
[10 21 33 46 60 75]


In [69]:
#Produit total
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])
print(x)

40320


In [70]:
#Produit axial
newarr = np.prod([arr1, arr2], axis=1)
print(newarr)

[  24 1680]


In [71]:
#Produit cumulatif
newarr = np.cumprod(arr1)
print(newarr)

[ 1  2  6 24]


In [72]:
#Différence discrète
#Une différence discrète signifie soustraire deux éléments successifs.
#Par exemple, pour [1, 2, 3, 4], la différence discrète serait 
#[2-1, 3-2, 4-3] = [1, 1, 1]
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

[  5  10 -20]


In [73]:
#PPCM
#pour deux nombres
num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print(x)

12


In [74]:
#pour tout un tableau
#La reduce()méthode utilisera le ufunc, dans ce cas la lcm()fonction, 
#sur chaque élément, et réduira le tableau d'une dimension.
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

18


In [75]:
#PGCD
#pour deux nombres
num1 = 4
num2 = 6
x = np.gcd(num1, num2)
print(x)

2


In [76]:
#pour tout un tableau
#La reduce()méthode utilisera le ufunc, dans ce cas la gcd()fonction, 
#sur chaque élément, et réduira le tableau d'une dimension.
arr = np.array([3, 6, 9])
x = np.gcd.reduce(arr)
print(x)

3


In [77]:
#Moyenne
arr = np.array([10, 15, 25, 5])
print(np.mean(arr))

13.75


In [78]:
#Déviation standard
print(np.std(arr))

7.39509972887452


In [79]:
#Variance
print(np.var(arr))
#Minimum
print(np.min(arr))
#Maximum
print(np.max(arr))

54.6875
5
25


#### Fonctions géométriques

In [80]:
#sur deux nombres
x = np.sin(np.pi/2)
print(x)
#de manière vectorielle
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)
#degrés en radians
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

1.0
[1.         0.8660254  0.70710678 0.58778525]
[1.57079633 3.14159265 4.71238898 6.28318531]


#### Tableaux ensembles

Leurs éléments ne seront pas répétés

In [81]:
#Création d'un tableau ensemble
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)
#Union 1d unique
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)
#Intersection unique
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)
#Différence unique
newarr = np.setdiff1d(arr1, arr2, assume_unique=True)
print(newarr)
#Différence symétrique unique
newarr = np.setxor1d(arr1, arr2, assume_unique=True)
print(newarr)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]


### Brodcasting

**What is broadcasting?**

La diffusion est une fonctionnalité de numpy qui permet d'effectuer
des opérations mathématiques entre des tableaux de formes(shape)
différentes.Ceci nous fait gagner en temps et espace, par exemple:

Si vous avez une matrice 3x3 (A) et vous voulez ajouter un tableau 1x3
,NumPy va ajouter (B) à chaque ligne de (A).


Condition nécessaire et suffisante
Afin de pouvoir diffuser(étirer), la taille  des axes correspondants(trailing) 
des deux tableaux doivent être égaux ou l'une d'elle doit être égale à 1.

Règles du Broadcasting
  * Règle 1 : si les deux tableaux n’ont pas le même nombre de dimensions(shape),
on ajoute une dimension à gauche au shape du tableau avec moins 
de “dimensions” ;
  * Règle 2 : si les deux tableaux ont une shape différente pour chaqu'une des
dimesions, le tableau avec une dimension égale à 1 est répété pour avoir
la même dimension de l’autre tableau ;
  * Règle 3 : une erreur est générée si toutes les dimensions des deux tableaux
sont différentes de nombres d'éléments(size) et ces derniers sont
différentes de 1,

In [82]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [83]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

### Fonctions d'agrégation

In [84]:
#Somme totale
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2])
print(newarr)

12


In [85]:
#Somme axiale
newarr = np.sum([arr1, arr2], axis=1)
print(newarr)

[6 6]


In [86]:
#Somme cumulée
#La somme cumulative signifie ajouter partiellement les éléments du tableau.
#Par exemple, la somme partielle de [1, 2, 3, 4] serait
#[1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
newarr = np.cumsum(arr1)
print(newarr)

[1 3 6]


In [87]:
#Produit total
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])
print(x)

40320


In [88]:
#Produit axial
newarr = np.prod([arr1, arr2], axis=1)
print(newarr)

[  24 1680]


In [89]:
#Produit cumulatif
newarr = np.cumprod(arr1)
print(newarr)

[ 1  2  6 24]


In [90]:
#Différence discrète
#Une différence discrète signifie soustraire deux éléments successifs.
#Par exemple, pour [1, 2, 3, 4], la différence discrète serait 
#[2-1, 3-2, 4-3] = [1, 1, 1]
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

[  5  10 -20]


In [91]:
#PPCM
#pour deux nombres
num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print(x)
#pour tout un tableau
#La reduce()méthode utilisera le ufunc, dans ce cas la lcm()fonction, 
#sur chaque élément, et réduira le tableau d'une dimension.
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)
#PGCD
#pour deux nombres
num1 = 4
num2 = 6
x = np.gcd(num1, num2)
print(x)
#pour tout un tableau
#La reduce()méthode utilisera le ufunc, dans ce cas la gcd()fonction, 
arr = np.array([3, 6, 9])
x = np.gcd.reduce(arr)
print(x)
#Moyenne
arr = np.array([10, 15, 25, 5])
print(np.mean(arr))
#Déviation standard
print(np.std(arr))
#Variance
print(np.var(arr))
#Minimum
print(np.min(arr))
#Maximum
print(np.max(arr))

12
18
2
3
13.75
7.39509972887452
54.6875
5
25


In [92]:
a = np.array([[np.nan, 55], [21, 13]])
b=np.array([[8, 4], [2, 1]])
#Retourne indice du min
print(np.argmin(a))
print(np.argmin(b))

0
3


In [93]:
#Retourne indice du min : ne prend pas nan en considération.
print(np.nanargmin(a))
print(np.nanargmin(b))

3
3


In [94]:
a = np.array([[np.nan, 55], [21, 13]])
b=np.array([[8, 4], [2, 1]])
#Retourne indice du max
#np.argmax si nan existe retourne l'indice de nan sinon celui du maximum
print(np.argmax(a),np.argmax(b)) 
#np.nanargmax ne prend pas nan en considération retourne l'indice du maximum.
print(np.nanargmax(a),np.nanargmax(b))

0 0
1 0


In [95]:
#Retourne median
#np.median si nan existe retourne nan
print(np.median(a),np.median(b)) 
#np.nanargmax ne prend pas nan en considération comme il n'existe pas.
print(np.nanmedian(a),np.nanmedian(b))

nan 3.0
21.0 3.0


In [96]:
"""Fonctions géométriques"""
#degrés en radians
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)


[1.57079633 3.14159265 4.71238898 6.28318531]


In [97]:
"""Tableaux ensembles
Leurs éléments ne seront pas répétés"""
#Création d'un tableau ensemble
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


In [98]:
#Union 1d unique
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)
#Intersection unique
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)
#Différence unique
newarr = np.setdiff1d(arr1, arr2, assume_unique=True)
print(newarr)
#Différence symétrique unique
newarr = np.setxor1d(arr1, arr2, assume_unique=True)
print(newarr)

[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]


# *FIN*